//
//  NXAuthenticationObject.swift
//  Cocinera
//
//  Created by Jon Alaniz on 2/19/23.
//

import Foundation

/// Contains Poll data and URL for authentication
struct AuthenticationObject: Decodable {
    /// Object containing polling url and token
    let poll: Poll?

    /// Login URL Generated by Nextcloud Server for the login session
    /// User will login at this address and server will return a NXServer object once authenticated
    let login: String?
}

struct Poll: Decodable {
    /// Poll Token, valid for 20 minutes after creation
    let token: String?

    /// Poll URL
    let endpoint: String?
}
